# Generated by Django 2.2.17 on 2020-11-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20201127_0527"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dddsfd",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fgfdhfghgjf", models.BigIntegerField()),
            ],
        ),
    ]
