# Generated by Django 2.2.17 on 2020-11-27 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_dddsfd"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customtext",
            old_name="hfghfghgh",
            new_name="hg",
        ),
        migrations.RemoveField(
            model_name="customtext",
            name="title",
        ),
    ]
