# Generated by Django 2.2.17 on 2020-11-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201127_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='ghgfhfg',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='hg',
        ),
    ]
